FROM farcasterxyz/hubble:latest

# Change to the Hubble app directory and create the network identity
WORKDIR /hubble/apps/hubble
RUN yarn identity create

CMD yarn start --eth-mainnet-rpc-url https://mainnet.infura.io/v3/b01863d44f1341cb9c334ee64c2d3379 --l2-rpc-url https://optimism-mainnet.infura.io/v3/b01863d44f1341cb9c334ee64c2d3379 --hub-operator-fid 11500
